### ISSUE TITLE
What server parameters do you use?

### ISSUE THREAD

**Issue by Julianoe** [Alligatore3/ftp-uploader#1]
Do you tweak your php.ini file? Or do you add a .htaccess file? I'm trying to implement a version of this to send files that are up to 1Go... What would you recommend as config server-side?

**Comment by Alligatore3** [comment]
Hi @Julianoe 

that's a huge file size.
Honestly I didn't try.
This example is close to small files size but yes I would try to edit my php.ini file.

[This example worked for me.](https://mediatemple.net/community/products/dv/204404784/how-do-i-increase-the-php-upload-limits)

Let me know.
Best

**Comment by Alligatore3** [comment]
Some infos:

` Apache version => 2.4.39
 PHP version => 5.6.40`
